In [17]:
import os
import pandas as pd
import alpaca_trade_api as tradeapi

In [2]:
# set Alpaca API key and secret
apca_api_key_id = os.getenv('APCA_API_KEY_ID')
apca_api_secret_key = os.getenv('APCA_API_SECRET_KEY')
# apca_api_key_id = ''
# apca_api_secret_key = ''

In [3]:
# create the Alpaca API object
alpaca = tradeapi.REST(
    apca_api_key_id,
    apca_api_secret_key,
    api_version='v2')

In [4]:
# Format start and end dates ISO format
end_date = pd.Timestamp('2022-08-07', tz='America/New_York').isoformat()
start_date = pd.Timestamp('2021-08-07', tz='America/New_York').isoformat()

# Set the tickers [Pfizer = PFE, Twitter = TWTR, Lockheed = LMT] 
tickers = ['PFE', 'TWTR', 'LMT']

# Set timeframe to "1Day" for Alpaca API
timeframe = "1D"

# Get current closing prices for SPY and AGG
df_tickers = alpaca.get_bars(
    tickers,
    timeframe,
    start = start_date,
    end = end_date
).df

In [5]:
# reorganize the DataFrame
# separate ticker data
PFE = df_tickers[df_tickers['symbol']=='PFE'].drop('symbol', axis=1)
TWTR = df_tickers[df_tickers['symbol']=='TWTR'].drop('symbol', axis=1)
LMT = df_tickers[df_tickers['symbol']=='LMT'].drop('symbol', axis=1)

# concatenate the ticker DataFrames
df_tickers = pd.concat([PFE, TWTR, LMT],axis=1, keys=['PFE','TWTR', 'LMT'])

df_tickers.head(10)

                             PFE                                             \
                            open   high    low  close    volume trade_count
timestamp
2021-08-09 04:00:00+00:00  45.21  46.03  45.11  45.98  32341383      164212
2021-08-10 04:00:00+00:00  46.00  48.57  45.89  48.19  81170248      376483
2021-08-11 04:00:00+00:00  47.88  48.08  46.26  46.31  50849787      272726
2021-08-12 04:00:00+00:00  46.46  47.40  46.34  47.24  29703568      164025
2021-08-13 04:00:00+00:00  47.42  48.50  47.32  48.48  35352240      193685
2021-08-16 04:00:00+00:00  48.29  48.97  47.51  48.91  38035416      212992
2021-08-17 04:00:00+00:00  48.79  50.49  48.71  50.42  68784595      380141
2021-08-18 04:00:00+00:00  50.20  51.86  49.17  49.31  88525968      472336
2021-08-19 04:00:00+00:00  48.82  49.96  48.26  48.80  57640354      325293
2021-08-20 04:00:00+00:00  49.03  49.73  48.66  48.72  35111006      184382

                                       TWTR                   ...            \
                                vwap   open     high     low  ...    volume
timestamp                                                     ...
2021-08-09 04:00:00+00:00  45.683125  67.37  67.5200  66.450  ...   7930848
2021-08-10 04:00:00+00:00  47.508634  67.15  67.3700  65.570  ...   8988493
2021-08-11 04:00:00+00:00  46.718284  65.69  66.3350  64.630  ...   8623218
2021-08-12 04:00:00+00:00  47.001033  65.03  65.2799  64.060  ...   7959222
2021-08-13 04:00:00+00:00  48.113933  65.00  65.7700  64.615  ...   6076607
2021-08-16 04:00:00+00:00  48.386097  64.50  64.9400  62.805  ...  11980862
2021-08-17 04:00:00+00:00  49.820440  63.18  63.8400  62.355  ...   6935397
2021-08-18 04:00:00+00:00  50.549726  63.07  63.3100  62.070  ...   6868563
2021-08-19 04:00:00+00:00  49.070636  61.59  63.1900  61.500  ...   8472808
2021-08-20 04:00:00+00:00  49.099522  62.13  63.1700  61.990  ...   8578096

                                                     LMT                     \
                          trade_count       vwap    open      high      low
timestamp
2021-08-09 04:00:00+00:00       71539  67.052398  360.70  362.4246  359.780
2021-08-10 04:00:00+00:00       82120  66.168530  360.19  363.0600  360.100
2021-08-11 04:00:00+00:00       85443  65.413307  362.45  364.3500  361.000
2021-08-12 04:00:00+00:00       77625  64.702347  362.33  364.3000  358.800
2021-08-13 04:00:00+00:00       48965  64.980221  360.25  361.0650  357.510
2021-08-16 04:00:00+00:00       89463  63.517749  357.98  360.5100  355.560
2021-08-17 04:00:00+00:00       63539  62.892842  359.05  362.5300  358.665
2021-08-18 04:00:00+00:00       53245  62.509361  359.50  360.5000  356.560
2021-08-19 04:00:00+00:00       79016  62.308156  355.23  359.8950  353.570
2021-08-20 04:00:00+00:00       64499  62.469776  354.74  358.8100  353.570


                            close   volume trade_count        vwap
timestamp
2021-08-09 04:00:00+00:00  361.04   944509       21977  361.017865
2021-08-10 04:00:00+00:00  362.24   840373       25792  361.637703
2021-08-11 04:00:00+00:00  363.30   910685       26300  362.733242
2021-08-12 04:00:00+00:00  359.75  1005066       27362  360.450373
2021-08-13 04:00:00+00:00  357.98  1221841       32907  358.421122
2021-08-16 04:00:00+00:00  360.25  1624413       39241  359.401311
2021-08-17 04:00:00+00:00  361.60  1569429       28657  361.174160
2021-08-18 04:00:00+00:00  356.60   958433       28040  358.444074
2021-08-19 04:00:00+00:00  354.03  1341094       37183  356.067676
2021-08-20 04:00:00+00:00  357.17   902024       26323  357.145864

[10 rows x 21 columns]

In [15]:
df_closing_prices = pd.DataFrame()
# fetch closing prices

df_closing_prices["PFE"] = df_tickers["PFE"]["close"]
df_closing_prices["TWTR"] = df_tickers["TWTR"]["close"]
df_closing_prices["LMT"] = df_tickers["LMT"]["close"]

df_closing_prices.index = df_closing_prices.index.date
df_closing_prices.head()

pandas.core.frame.DataFrame

In [24]:
unstacked = df_closing_prices.unstack()
df_PFE = pd.DataFrame(df_closing_prices["PFE"])
df_PFE.to_csv('pfe_historical.csv')
df_TWTR = pd.DataFrame(df_closing_prices["TWTR"])
df_TWTR.to_csv('twtr_historical.csv')
df_LMT = pd.DataFrame(df_closing_prices["LMT"])
df_LMT.to_csv('lmt_historical.csv')